### ISSUE TITLE
Replace @extends with @mixins

### ISSUE THREAD

**Issue by robinpoort** [timble/timble-illusion#2]
See:
http://www.sitepoint.com/avoid-sass-extend/
http://csswizardry.com/2014/11/when-to-use-extend-when-to-use-a-mixin/

Basically, when GZIP'ing CSS the file size doesn't really make a difference.
Why @mixin besides that?
1. You can use @mixin within @media-queries
2. The CSS is being included and not put somewhere in a list. This is better when inspecting with dev toolbars

**Comment by robinpoort** [comment]
@tomjanssens This can be closed?

**Comment by tomjanssens** [comment]
I think so.

**Comment by robinpoort** [comment]
Yeah it's all mixins now..
